src/Entity/Commande.php
<?php

namespace App\Entity;

use App\Repository\CommandeRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommandeRepository::class)]
class Commande
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'commandes')]
    #[ORM\JoinColumn(nullable: false)]
    private $id_membre;

    #[ORM\ManyToOne(targetEntity: Vehicule::class, inversedBy: 'commandes')]
    #[ORM\JoinColumn(nullable: false)]
    private $id_vehicule;

    #[ORM\Column(type: 'datetime')]
    private $date_heure_depart;

    #[ORM\Column(type: 'datetime')]
    private $date_heure_fin;

    #[ORM\Column(type: 'integer')]
    private $prix_total;

    #[ORM\Column(type: 'datetime')]
    private $date_enregistrement;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdMembre(): ?User
    {
        return $this->id_membre;
    }

    public function setIdMembre(?User $id_membre): self
    {
        $this->id_membre = $id_membre;

        return $this;
    }

    public function getIdVehicule(): ?Vehicule
    {
        return $this->id_vehicule;
    }

    public function setIdVehicule(?Vehicule $id_vehicule): self
    {
        $this->id_vehicule = $id_vehicule;

        return $this;
    }

    public function getDateHeureDepart(): ?\DateTimeInterface
    {
        return $this->date_heure_depart;
    }

    public function setDateHeureDepart(\DateTimeInterface $date_heure_depart): self
    {
        $this->date_heure_depart = $date_heure_depart;

        return $this;
    }

    public function getDateHeureFin(): ?\DateTimeInterface
    {
        return $this->date_heure_fin;
    }

    public function setDateHeureFin(\DateTimeInterface $date_heure_fin): self
    {
        $this->date_heure_fin = $date_heure_fin;

        return $this;
    }

    public function getPrixTotal(): ?int
    {
        return $this->prix_total;
    }

    public function setPrixTotal(int $prix_total): self
    {
        $this->prix_total = $prix_total;

        return $this;
    }

    public function getDateEnregistrement(): ?\DateTimeInterface
    {
        return $this->date_enregistrement;
    }

    public function setDateEnregistrement(\DateTimeInterface $date_enregistrement): self
    {
        $this->date_enregistrement = $date_enregistrement;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 180, unique: true)]
    private $email;

    #[ORM\Column(type: 'json')]
    private $roles = [];

    #[ORM\Column(type: 'string')]
    private $password;

    #[ORM\Column(type: 'string', length: 255)]
    private $pseudo;

    #[ORM\Column(type: 'string', length: 255)]
    private $nom;

    #[ORM\Column(type: 'string', length: 255)]
    private $prenom;

    #[ORM\Column(type: 'string', length: 255)]
    private $civilite;

    #[ORM\Column(type: 'datetime')]
    private $date_enregistrement;

    #[ORM\OneToMany(mappedBy: 'id_membre', targetEntity: Commande::class)]
    private $commandes;

    public function __construct()
    {
        $this->commandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getCivilite(): ?string
    {
        return $this->civilite;
    }

    public function setCivilite(string $civilite): self
    {
        $this->civilite = $civilite;

        return $this;
    }

    public function getDateEnregistrement(): ?\DateTimeInterface
    {
        return $this->date_enregistrement;
    }

    public function setDateEnregistrement(\DateTimeInterface $date_enregistrement): self
    {
        $this->date_enregistrement = $date_enregistrement;

        return $this;
    }

    /**
     * @return Collection<int, Commande>
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): self
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes[] = $commande;
            $commande->setIdMembre($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): self
    {
        if ($this->commandes->removeElement($commande)) {
            // set the owning side to null (unless already changed)
            if ($commande->getIdMembre() === $this) {
                $commande->setIdMembre(null);
            }
        }

        return $this;
    }
}

src/Entity/Vehicule.php
<?php

namespace App\Entity;

use App\Repository\VehiculeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: VehiculeRepository::class)]
class Vehicule
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $titre;

    #[ORM\Column(type: 'string', length: 255)]
    private $marque;

    #[ORM\Column(type: 'string', length: 255)]
    private $modele;

    #[ORM\Column(type: 'text')]
    private $description;

    #[ORM\Column(type: 'string', length: 255)]
    private $photo;

    #[ORM\Column(type: 'integer')]
    private $prix_journalier;

    #[ORM\Column(type: 'datetime')]
    private $dete_enregistrement;

    #[ORM\OneToMany(mappedBy: 'id_vehicule', targetEntity: Commande::class)]
    private $commandes;

    #[ORM\OneToMany(mappedBy: 'vehicule', targetEntity: Media::class)]
    private $media;

    public function __construct()
    {
        $this->commandes = new ArrayCollection();
        $this->media = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getMarque(): ?string
    {
        return $this->marque;
    }

    public function setMarque(string $marque): self
    {
        $this->marque = $marque;

        return $this;
    }

    public function getModele(): ?string
    {
        return $this->modele;
    }

    public function setModele(string $modele): self
    {
        $this->modele = $modele;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    public function getPrixJournalier(): ?int
    {
        return $this->prix_journalier;
    }

    public function setPrixJournalier(int $prix_journalier): self
    {
        $this->prix_journalier = $prix_journalier;

        return $this;
    }

    public function getDeteEnregistrement(): ?\DateTimeInterface
    {
        return $this->dete_enregistrement;
    }

    public function setDeteEnregistrement(\DateTimeInterface $dete_enregistrement): self
    {
        $this->dete_enregistrement = $dete_enregistrement;

        return $this;
    }

    /**
     * @return Collection<int, Commande>
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): self
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes[] = $commande;
            $commande->setIdVehicule($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): self
    {
        if ($this->commandes->removeElement($commande)) {
            // set the owning side to null (unless already changed)
            if ($commande->getIdVehicule() === $this) {
                $commande->setIdVehicule(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Media>
     */
    public function getMedia(): Collection
    {
        return $this->media;
    }

    public function addMedium(Media $medium): self
    {
        if (!$this->media->contains($medium)) {
            $this->media[] = $medium;
            $medium->setVehicule($this);
        }

        return $this;
    }

    public function removeMedium(Media $medium): self
    {
        if ($this->media->removeElement($medium)) {
            // set the owning side to null (unless already changed)
            if ($medium->getVehicule() === $this) {
                $medium->setVehicule(null);
            }
        }

        return $this;
    }
}

src/Controller/Front/FrontAcceuilController.php
<?php

namespace App\Controller\Front;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class FrontAcceuilController extends AbstractController
{
    #[Route('/', name: 'app_front_acceuil')]
    public function index(): Response
    {
        return $this->render('front/acceuil.html.twig', [
            'controller_name' => 'FrontAcceuilController',
        ]);
    }
}

src/Controller/Front/FrontCommandeController.php
<?php

namespace App\Controller\Front;

use App\Entity\Commande;
use App\Form\CommandeFormType;
use App\Repository\CommandeRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;


class FrontCommandeController extends AbstractController
{
    /**
     * @Route("/commandes", name="commande_list")
     */
    public function commandeList(CommandeRepository $commandeRepository)
    {
        $commandes = $commandeRepository->findAll();

        return $this->render("front/commande_list.html.twig", ['commandes' => $commandes]);
    }


    /**
     * @Route("/commande/{id}", name="commande_show")
     */
    public function commandeShow($id, CommandeRepository $commandeRepository)
    {
        $commande = $commandeRepository->find($id);

        return $this->render("front/commande_show.html.twig", ['commande' => $commande]);
    }

    /**
     * @Route("/create/commande", name="commande_create")
     */
    public function createCommande( EntityManagerInterface $entityManagerInterface, Request $request)
    {
        $commande = New Commande();

        $commandeForm = $this->createForm(CommandeFormType::class, $commande);
        
        // $membre = $userRepository->find($id);
        // $membre = $userRepository->get('email')->getData();

        // $membre = $commandeForm["id_membre"]->getData(email);
        // $commandeForm["id_membre,email"]->getData();
        // $membre = $this->get('email')->getData(); 


        // if(function_exists('date_between'))
        //     public function dateBetween($date_start, $date_end)
        //     {
        //         if(!$date_start || !$date_end) return 0;
       
         
        //         if( class_exists('DateTime') )
        //         {   
        //             $date_start = new DateTime( $date_start );
        //             $date_end = new DateTime( $date_end );
        //             return $date_end->diff($date_start)->format('%a');
        //          }else{           
        //             return abs( round( ( strtotime($date_start) - strtotime($date_end) ) / 86400 ) );
        //         }
            
        //     } endif;

        //     $valeurdate = $commandeForm->get('date_between')->getData();
            
        //     $valeurPrixJournalier = $vehicule->get('prix_journalier');

        //     $valeurprix = ('prixJournalier') * ('date_beetween');


        
        $commandeForm->handleRequest($request);

        if($commandeForm->isSubmitted() && $commandeForm->isValid()){

            $entityManagerInterface->persist($commande);
            $entityManagerInterface->flush();

            return $this->redirectToRoute("commande_list");
        }

        return $this->render("front/commande_form.html.twig", ['commandeForm' => $commandeForm->createView()]);
    }


}

src/Controller/Front/FrontHomeController.php
<?php

namespace App\Controller\Front;

use App\Repository\VehiculeRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class FrontHomeController extends AbstractController
{
    /**
     * @Route("search/", name="front_search")
     */
    public function search(VehiculeRepository $vehiculeRepository, Request $request)
    {
        $term = $request->query->get('term');
        $vehicules = $vehiculeRepository->searchByterm($term);

        return $this->render("front/search.html.twig", ['vehicules' => $vehicules, 'term' => $term]);
    }
}

src/Controller/Front/FrontUserController.php
<?php

namespace App\Controller\Front;

use App\Entity\User;
use App\Form\UserFormType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;

class FrontUserController extends AbstractController
{
    /**
     * @Route("/user/insert", name="insert_user")
     */
    public function insertUser(
        Request $request,
        EntityManagerInterface $entityManagerInterface,
        UserPasswordHasherInterface $userPasswordHasherInterface
    ) {
        $user = new User();

        $userForm = $this->createForm(UserFormType::class, $user);

        $userForm->handleRequest($request);

        if ($userForm->isSubmitted() && $userForm->isValid()) {
            $user->setRoles(["ROLE_USER"]);

            $plainPassword = $userForm->get('password')->getData();

            $hashedPassword = $userPasswordHasherInterface->hashPassword($user, $plainPassword);
            $user->setPassword($hashedPassword);

            $entityManagerInterface->persist($user);
            $entityManagerInterface->flush();

            return $this->redirectToRoute('app_login');
        }

        return $this->render('front/user_form.html.twig', ['userForm' => $userForm->createView()]);
    }
}

templates/front/acceuil.html.twig
{% extends "front/base.html.twig" %}

{% block main %}

{# navbar validé #}
<nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-between">  

    <div class="container">
    <a class="navbar-brand" href="{{ path('app_front_acceuil')}}">Acceuil</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" 
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                     <a class="nav-link" href="{{ path('vehicule_list')}}">Nos Véhicules<span class="sr-only"></span></a>
                </li>
                <li class="nav-item active">
                     <a class="nav-link" href="{{ path('insert_user')}}">Inscription<span class="sr-only"></span></a>
                </li>
                <li class="nav-item active">
                     <a class="nav-link" href="{{ path('app_login')}}">Connexion<span class="sr-only"></span></a>
                </li>
                <li class="nav-item active">
                     <a class="nav-link" href="{{ path('app_logout')}}">Déconnexion<span class="sr-only"></span></a>
                </li>
                {# <li class="nav-item active">
                     <a class="nav-link" href="{{ path('commande_list')}}">Historiques des commandes<span class="sr-only"></span></a>
                </li> #}
            </ul>
        </div>
    </div>
</nav>


<div class="">
    <img class="img-fluid" src="{{asset('images/fond2.png')}}" alt="fond d'écran ">
    <div class="texte_center">
        <h1>Bienvenue à bord</h1>
        <p>Location de voiture 24h/24 et 7j/7.</p>
        <form action="{{path('front_search') }}" method="get">
	        <label for="term"></label>
	        <input type="search" name="term" id="term">
	        <input type="submit" value="Chercher">
        </form> 
    </div>
</div>

<style>
.img-fluid {
  position: relative;
  color: black;
}

.texte_center {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  color: white;
  text-align: center;
}
</style>

{% endblock %}

templates/front/base.html.twig
<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link rel="stylesheet" href="{{asset('public/css/style.css')}}">
        <script src="https://kit.fontawesome.com/f668cda814.js" crossorigin="anonymous"></script>
		<title>Agence de location</title>
	</head>
	<body>

		<header>
			{# <form action="{{path('front_search') }}" method="get">
				<label for="term"></label>
				<input type="search" name="term" id="term">
				<input type="submit" value="Chercher">
			</form> #}
		</header>

		<main>
			{% block main %}{% endblock %}
		</main>


	</body>
</html>

templates/front/commande_form.html.twig
{% extends "front/base.html.twig" %}

{% block main %}

<nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-between">  

    <div class="container">
    <a class="navbar-brand" href="{{ path('app_front_acceuil')}}">Acceuil</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" 
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                     <a class="nav-link" href="{{ path('vehicule_list')}}">Nos Véhicules<span class="sr-only"></span></a>
                </li>
                <li class="nav-item active">
                     <a class="nav-link" href="{{ path('commande_list')}}">Historiques des commandes<span class="sr-only"></span></a>
                </li>
                <li class="nav-item active">
                     <a class="nav-link" href="{{ path('app_logout')}}">Déconnexion<span class="sr-only"></span></a>
                </li>
            </ul>
        </div>
    </div>
</nav>




{{form_start(commandeForm)}}
<div class="container">
<h2>Formulaire de commande</h2>
    <div class="form-group">
        {{form_label(commandeForm.id_membre, ' Membre :')}}
        {{form_widget(commandeForm.id_membre, {'attr':{'class':'form-control'}} )}}
    </div>
    <div>
        {{form_label(commandeForm.id_vehicule, ' Véhicule :')}}
        {{form_widget(commandeForm.id_vehicule, {'attr':{'class':'form-control'}})}}
    </div>
    <div>
        {{form_label(commandeForm.date_heure_depart, ' Date et heure de départ :')}}
        {{form_widget(commandeForm.date_heure_depart)}}
    </div>
    <div>
        {{form_label(commandeForm.date_heure_fin, ' Date et heure de fin :')}}
        {{form_widget(commandeForm.date_heure_fin)}}
    </div>
    <div>
        {{form_label(commandeForm.prix_total, ' Prix Total :')}}
        {{form_widget(commandeForm.prix_total, {'attr':{'class':'form-control'}})}}
    </div>
    <div>
        {{form_label(commandeForm.date_enregistrement, ' Date et heure d\'enregistrement :')}}
        {{form_widget(commandeForm.date_enregistrement)}}
    </div>
    <br>
    <div>
        {{form_widget(commandeForm.Enregistrer, {'attr':{'class':'bibi'}})}}
    </div>
</div>
{{form_end(commandeForm)}}

<style>
.bibi{
    background-color: white; 
    border-radius: 4px ;
    color: black;
    padding: 10px 20px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
}

.bibi:hover{
    background-color: #D0BEBB;
    color: white
}

</style>

{% endblock %}

templates/front/commande_list.html.twig
{% extends "front/base.html.twig" %}

{% block main %}

<nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-between">  

    <div class="container">
    <a class="navbar-brand" href="{{ path('app_front_acceuil')}}">Acceuil</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" 
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                     <a class="nav-link" href="{{ path('vehicule_list')}}">Nos Véhicules<span class="sr-only"></span></a>
                </li>
                <li class="nav-item active">
                     <a class="nav-link" href="{{ path('app_logout')}}">Déconnexion<span class="sr-only"></span></a>
                </li>
            </ul>
        </div>
    </div>
</nav>


<h2>Historiques des commandes</h2>


<div class="container row g-3 align-items-center">
<table class="table">
    <thead>
        <tr>
            <th scope="col">Commande</th>
            <th scope="col">Véhicule</th>
            <th scope="col">Date et heure de départ</th>
            <th scope="col">Date et heure de fin</th>
            <th scope="col">Prix total</th>
            <th scope="col">Date et heure d'enregistrement</th>
        </tr>
    </thead>
    <tbody>
    {% for commande in commandes %}
        <tr>
            <th scope="row"><a href="{{ path('commande_show', {'id': commande.id } ) }}" style="color: black">{{ commande.id }}</a></th>
            <td>{{commande.idVehicule}}</td>
            <td>{{commande.dateHeureDepart}}</td>
            <td>{{commande.dateHeureFin}}</td>
            <td>{{commande.prixTotal}}</td>
            <td>{{commande.dateEnregistrement}}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
</div>

{% endblock %}

templates/front/commande_show.html.twig
{% extends "front/base.html.twig" %}

{% block main %} 

<nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-between">  

    <div class="container">
    <a class="navbar-brand" href="{{ path('app_front_acceuil')}}">Acceuil</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" 
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                     <a class="nav-link" href="{{ path('vehicule_list')}}">Nos Véhicules<span class="sr-only"></span></a>
                </li>
                <li class="nav-item active">
                     <a class="nav-link" href="{{ path('commande_list')}}">Historiques des commandes<span class="sr-only"></span></a>
                </li>
                <li class="nav-item active">
                     <a class="nav-link" href="{{ path('app_logout')}}">Déconnexion<span class="sr-only"></span></a>
                </li>
            </ul>
        </div>
    </div>
</nav>


<h2>Voici la commande {{commande.id}}</h2>

<div class="container row g-3 align-items-center">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Commande</th>
                <th scope="col">Véhicule</th>
                <th scope="col">Date et heure de départ</th>
                <th scope="col">Date et heure de fin</th>
                <th scope="col">Prix total</th>
                <th scope="col">Date et heure d'enregistrement</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th>{{commande.id}}</th>
                <td>{{commande.idVehicule}}</td>
                <td>{{commande.dateHeureDepart}}</td>
                <td>{{commande.dateHeureFin}}</td>
                <td>{{commande.prixTotal}}</td>
                <td>{{commande.dateEnregistrement}}</td>
            </tr>
        </tbody>
    </table>
</div>

{% endblock %}

templates/front/search.html.twig
{% extends "front/base.html.twig" %}

{% block main %}

<nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-between">  

    <div class="container">
    <a class="navbar-brand" href="{{ path('app_front_acceuil')}}">Acceuil</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" 
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                     <a class="nav-link" href="{{ path('vehicule_list')}}">Nos Véhicules<span class="sr-only"></span></a>
                </li>
                <li class="nav-item active">
                     <a class="nav-link" href="{{ path('commande_list')}}">Historiques des commandes<span class="sr-only"></span></a>
                </li>
                <li class="nav-item active">
                     <a class="nav-link" href="{{ path('app_logout')}}">Déconnexion<span class="sr-only"></span></a>
                </li>
            </ul>
        </div>
    </div>
</nav>


<h2>Les vehicules qui correspondent à votre recherche "{{ term }}" sont :</h2>

<div class="container row g-3 align-items-center">
<table class="table">
    <tbody>
        {% for vehicule in vehicules %}
        <tr>
            <td><img src="{{ asset("media/" ~ vehicule.media[0].src) }}" alt="{{ vehicule.media[0].alt }}"></td>
            <td><a href="{{ path("vehicule_show", {'id' : vehicule.id })}}" style="color: black">
            <h3><br><br>{{ vehicule.titre}}</h3>
            {{vehicule.description}}
            <br>
            {{vehicule.prixJournalier}}€</a>
            <br><br>
            <a href="{{ path('commande_create')}}" class="btn btn-outline-secondary">Passez une commande</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
</div>


 
<style>
a{
text-decoration:none;
}
</style>

{% endblock %}